config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'users#index'

    resources :users do
      resources :questions, only: %i[create destroy] do
        resource :anwser, only: %i[create destroy]
      end
    end

    resource :session, only: %i[new create destroy]
  end
end

app/models/anwser.rb
class Anwser < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_one :anwser, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :questions, dependent: :destroy
  has_one_attached :avatar

  validates :nickname, presence: true
  validates :email, presence: true

  validates_uniqueness_of :email
  validates_uniqueness_of :nickname
end

app/controllers/anwsers_controller.rb
class AnwsersController < ApplicationController
  before_action :set_params

  def create
    return unless have_permission?

    @anwser = Anwser.create(question_id: params[:question_id], body: params[:body])

    respond_to do |format|
      if @anwser.save
        format.html do
          redirect_to user_question_path(user_id: @question.user.id, id: @question.id),
                      notice: 'Anwser was successfully created.'
        end
      else
        format.html do
          redirect_to user_question_path(user_id: @question.user.id, id: @question.id),
                      notice: 'Errors while anwser creating.'
        end
      end
    end
  end

  def destroy
    return unless have_permission?

    Anwser.where(question_id: params[:question_id]).destroy_all

    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Anwser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def have_permission?
    @question.user == current_user
  end

  def set_params
    @user = User.find(params[:user_id])
    @question = Question.find(params[:question_id])
  end

  def anwser_params
    params.require(:anwser).permit(:question_id, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :set_locale

  protected

  def default_url_options
    { host: 'localhost', port: 3000, locale: I18n.locale }
  end

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    return unless I18n.available_locales.map(&:to_s).include?(parsed_locale)

    parsed_locale.to_sym
  end

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_user

  # POST /questions or /questions.json
  def create
    @question = @user.questions.create(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to user_path(@user), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { redirect_to user_path(@user), notice: 'Errors while question creating' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question = @user.questions.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(:user_id, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])
    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль'
      render :new
    end
  end

  def destroy 
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :have_permission?, only: %i[edit destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @questions = @user.questions.order(created_at: :desc)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to user_path(@user), notice: 'Ypu dont have permissions' unless have_permission?
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    return unless have_permission?

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    return unless have_permission?

    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  def have_permission?
    current_user == @user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/anwsers/_anwser.html.erb
<% if question.anwser.presence %>
    <div class="anwser">
        <div class = "mb-sm d-space-between" >
          <%= question.anwser.body %>
              <% if question.user == current_user %>
                <%= button_to inline_svg_tag("delete.svg", class: 'svg-picture delete'), user_question_anwser_path(user_id: question.user.id, question_id: question.id), method: :delete, class: "button delete" %>
              <% end %>
        </div>

        <div class = "text-sm question-footer" >
          <div class="text-grey" >
            <%= question.anwser.created_at %>
          </div>
        </div>
    </div>
<% end %>

app/views/anwsers/_form.html.erb
<div class="border_form">
  <%= form_with url: user_question_anwser_path(question_id: question.id, user_id: question.user.id) do |form| %>

    <p><%= form.label :body, 'Текст ответа:'%></p>
    <p><%= form.text_field :body, rows: 5, class: 'form-text-area' %></p>
    <p class="mt"><%= form.submit 'Ответить', class: 'button button-main' %></p>

  <% end %>
</div>

app/views/layouts/_avatar.html.erb
<div class="avatar">
<% if user.avatar.attached? %>
    <%= link_to (image_tag user.avatar, class: avatar_class), user_path(user) %>
<% else %>
    <%= link_to (image_tag 'default_avatar.jpg', class: avatar_class), user_path(user) %>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
    <div class = "wrapper">
      <div class = "navbar">
        <p class="title-sm text-bold">
          <%=link_to "Ask me!", root_path %>
            <%= link_to "Ru", url_for( :locale => 'ru' ), class: 'nav-link' %>
            <%= link_to "En", url_for( :locale => 'en' ), class: 'nav-link' %>
        </p>

        <div>
          <% if current_user.present? %>
          <div class="line">
            <div class="container">
              <%= render 'layouts/avatar', user: current_user, avatar_class: "avatar-navbar" %>
            </div>            
            <%= button_to 'Выйти', session_path, method: :delete , class:'button button-green' %>
          </div>

          <% else %>
            <%= link_to (t 'Sign up'), new_user_path, class: 'button button-green mr-sm'%>
            <%= link_to 'Вход', new_session_path, class: 'button button-green' %>
          <% end %>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zachetnya</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message-alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
    <script>
    imgInp.onchange = evt => {
    const [file] = imgInp.files
    if (file) {
        blah.src = URL.createObjectURL(file)
    }
    }
  </script>
</html>

app/views/questions/_form.html.erb
<div class="border_form">
  <h2>Задай свой вопрос</h2>
  <%= form_with(model: [user, question]) do |form| %>
    <% if question.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

        <ul>
          <% question.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p><%= form.label :body, 'Текст вопроса:'%></p>
    <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>
    <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>

  <% end %>
</div>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>" class="question">
  <div class = "mb-sm d-flex-start">
    <%= question.body %>
    <% if question.anwser.nil? && question.user == current_user %>
      <%= link_to inline_svg_tag("reply.svg", class: 'svg-picture reply'), nil, remote: true,
        data: { controller: "anwser",
                action: "anwser#toggleForm",
                anwser_form_param: "anwser_form_#{question.id}" } %>
    <% end %>    
  </div>

  <div class = "text-sm question-footer" >
    <div class="text-grey" >
      <%= question.created_at %>
    </div>
  </div>

  <%= render 'anwsers/anwser', question: question, user: user %>

  <div id="anwser_form_<%= question.id %>" class="d-none">
    <% if question.anwser.nil? %>
      <div class="anwser_form">
        <%= render 'anwsers/form', question: question %> 
      </div>
    <% end %>  
  </div>
</div>

app/views/users/_avatar.html.erb
    <div class="avatar">
    <% if user.avatar.attached? %>
            <%= image_tag user.avatar, class: avatar_class %>
    <% else %>
            <% if user == current_user %>
                <%= link_to (image_tag 'default_avatar.jpg', class: avatar_class), edit_user_path(user) %>
            <% else %>
                <%= image_tag 'default_avatar.jpg', class: avatar_class %>
            <% end %>
    <% end %>
    </div>

app/views/users/_buttons.html.erb
<div>
  <%= link_to "Редактировать профиль", edit_user_path(current_user), class: "button button-main" %> |
  <%= button_to "Удалить аккаунт", current_user, method: :delete, class: "button button-main" %>
</div>

app/views/users/_edit_form.html.erb
  <div class = "mt" >
    <%= form_with model: user, method: :put do |form| %>
      <% if user.errors.any? %>
        <div style="color: red">
          <ul>
            <% user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p class = 'mt' ><%= form.label :name, 'Ваше имя:' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class = 'mt' ><%= form.label :nickname, 'Ник на сайте:' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class = 'mt' ><%= form.label :email, 'Электронная почта' %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class = 'mt' ><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field', required: "" %></p>
      
      <div class="row">
         <div class="field">
           <%= form.label :avatar, (t 'Profile photo') %>
           <%= form.file_field :avatar, :id => "imgInp", data: { controller: "img-preview" } %>
         </div>
         <div class="field">
           <%= image_tag 'default_preview.png', id: 'blah', class: 'avatar-mini' %>
         </div>
      </div>

      <p class = 'mt-lg' ><%= form.submit 'Обновить', class: 'button button-main'%></p>
    <% end %>

  </div>

app/views/users/_form.html.erb
  <div class = "mt" >
    <%= form_with model: @user do |form| %>
      <% if @user.errors.any? %>
        <div style="color: red">
          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p class = 'mt' ><%= form.label :name, 'Ваше имя:' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class = 'mt' ><%= form.label :nickname, 'Ник на сайте:' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class = 'mt' ><%= form.label :email, 'Электронная почта' %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class = 'mt' ><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class = 'mt-lg' ><%= form.submit 'Зарегистрироваться', class: 'button button-main'%></p>
    <% end %>

  </div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <div class = "mb-sm d-flex-start" >
    <div class="nickname">
      <%= link_to user.nickname, user_path(user) %>
    </div>

    <%= render 'layouts/avatar', user: user, avatar_class: "avatar-mini" %>
  </div>
  
  <div class = "text-sm question-footer" >
    <div class="text-grey" >
      <%= user.name %>
       с нами уже с <%=l(user.created_at, format: :short) %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class = "container" >
  <h2 class = "title"> Редактировать </h2>
  <%= render "edit_form", user: @user %>
</div>


<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <div class = "mt-sm container" >
      <%= render user %>
    </div> 
  <% end %>
</div>

app/views/users/new.html.erb
<div class = "container" >
  <h2 class = "title"> Присоединяйся и спрашивай!</h2>
  <%= render "form", user: @user %>
</div>

app/views/users/show.html.erb
<div class = "container title-lg" >
  <p>Профиль пользователя: <%= @user.name %></p>
  <%= render 'avatar', user: @user, avatar_class: "avatar-big" %>
  <p class="text-sm question-footer"><%= (t "Registred at") %> <%=l(@user.created_at, format: :short) %></p>
  <% if current_user == @user %>
    <%= render 'users/buttons' %>
  <% end %>
</div>

 <div class = "mt-sm container" >
  <div class = "mt-sm" >
    <div class = "title-lg">
      <%= (t "question", count: @questions.count) %>
      <%= link_to (t "Ask"), nil, remote: true, class: "button button-main",
           data: { controller: "question",
                   action: "question#toggleForm" } %>
    </div>
  </div>

  <div id="question_form" class="d-none">
    <%= render 'questions/form', user: @user, question: @user.questions.build %>
  </div>

  <div id="questions">
    <% @questions.each do |question| %>
        <%= render 'questions/question', user: @user, question: question %>
    <% end %>
  </div>


</div>